name: qatch_nanoflux_24_well_plate
brand: QATCH Technologies
well_geometry:
  shape: circular
  diameter_mm: 0.75
  depth_mm: 19.9
  bottom: flat
  max_volume_ul: 6
wells:
  A1: { x: 17.8,   y: 51.0,  z: 95 }
  B1: { x: 16.8,   y: 40.8,  z: 95 }
  C1: { x: 17.1,   y: 31.87, z: 95 }
  D1: { x: 17.4,   y: 23.55, z: 95 }
  A2: { x: 29.63,  y: 47.1,  z: 95 }
  B2: { x: 29.43,  y: 37.9,  z: 95 }
  C2: { x: 29.23,  y: 28.97, z: 95 }
  D2: { x: 29.23,  y: 20.05, z: 95 }
  A3: { x: 54.2,   y: 50.0,  z: 95 }
  B3: { x: 54.1,   y: 40.9,  z: 95 }
  C3: { x: 54.4,   y: 32.47, z: 95 }
  D3: { x: 54.4,   y: 23.55, z: 95 }
  A4: { x: 67.33,  y: 46.5,  z: 95 }
  B4: { x: 67.23,  y: 38.1,  z: 95 }
  C4: { x: 67.23,  y: 28.97, z: 95 }
  D4: { x: 67.23,  y: 20.05, z: 95 }
  A5: { x: 91.6,   y: 49.8,  z: 95 }
  B5: { x: 91.9,   y: 40.89, z: 95 }
  C5: { x: 92.1,   y: 32.27, z: 95 }
  D5: { x: 91.6,   y: 23.85, z: 95 }
  A6: { x: 105.23, y: 46.8,  z: 95 }
  B6: { x: 105.23, y: 37.89, z: 95 }
  C6: { x: 105.23, y: 28.97, z: 95 }
  D6: { x: 105.23, y: 20.05, z: 95 }
